"""
Django admin configuration for Statepopulation.

Generated by SDCStudio AppGen for wizard-based architecture.
"""
from django.contrib import admin
from django.utils.html import format_html
from .models import StatepopulationInstance


@admin.register(StatepopulationInstance)
class StatepopulationInstanceAdmin(admin.ModelAdmin):
    """
    Admin interface for Statepopulation instances.

    Provides read-only view of instance data. Data entry should be done
    through the wizard interface, not directly in admin.
    """

    list_display = [
        'instance_id',
        'validation_status_badge',
        'rdf_sync_status_badge',
        'created_at',
        'updated_at',
    ]
    list_filter = ['validation_status', 'rdf_sync_status', 'created_at']
    search_fields = ['instance_id', 'search_text']
    ordering = ['-created_at']
    date_hierarchy = 'created_at'

    # All fields are read-only - data entry is through the wizard
    readonly_fields = [
        'instance_id',
        'xml_content_preview',
        'json_instance_preview',
        'search_text',
        'validation_status',
        'validation_errors_display',
        'auto_corrected_fields_display',
        'fuseki_graph_uri',
        'rdf_uploaded_at',
        'rdf_sync_status',
        'created_at',
        'updated_at',
    ]

    fieldsets = (
        ('Instance', {
            'fields': ('instance_id', 'created_at', 'updated_at'),
        }),
        ('Validation', {
            'fields': ('validation_status', 'validation_errors_display', 'auto_corrected_fields_display'),
        }),
        ('RDF/Triplestore', {
            'fields': ('rdf_sync_status', 'fuseki_graph_uri', 'rdf_uploaded_at'),
            'classes': ('collapse',),
        }),
        ('Content', {
            'fields': ('xml_content_preview', 'json_instance_preview', 'search_text'),
            'classes': ('collapse',),
        }),
    )

    def validation_status_badge(self, obj):
        """Display validation status as a colored badge."""
        colors = {
            'valid': 'green',
            'valid_with_ev': 'orange',
        }
        color = colors.get(obj.validation_status, 'gray')
        return format_html(
            '<span style="background-color: {}; color: white; padding: 3px 8px; '
            'border-radius: 3px; font-size: 11px;">{}</span>',
            color, obj.get_validation_status_display()
        )
    validation_status_badge.short_description = 'Validation'
    validation_status_badge.admin_order_field = 'validation_status'

    def rdf_sync_status_badge(self, obj):
        """Display RDF sync status as a colored badge."""
        colors = {
            'synced': 'green',
            'pending': 'orange',
            'failed': 'red',
            'disabled': 'gray',
        }
        color = colors.get(obj.rdf_sync_status, 'gray')
        return format_html(
            '<span style="background-color: {}; color: white; padding: 3px 8px; '
            'border-radius: 3px; font-size: 11px;">{}</span>',
            color, obj.get_rdf_sync_status_display()
        )
    rdf_sync_status_badge.short_description = 'RDF'
    rdf_sync_status_badge.admin_order_field = 'rdf_sync_status'

    def xml_content_preview(self, obj):
        """Show truncated XML content."""
        content = obj.xml_content[:2000] + '...' if len(obj.xml_content) > 2000 else obj.xml_content
        return format_html('<pre style="max-height: 300px; overflow: auto;">{}</pre>', content)
    xml_content_preview.short_description = 'XML Content'

    def json_instance_preview(self, obj):
        """Show formatted JSON instance."""
        import json
        try:
            formatted = json.dumps(obj.json_instance, indent=2, ensure_ascii=False)
            if len(formatted) > 2000:
                formatted = formatted[:2000] + '...'
            return format_html('<pre style="max-height: 300px; overflow: auto;">{}</pre>', formatted)
        except Exception:
            return str(obj.json_instance)
    json_instance_preview.short_description = 'JSON Instance'

    def validation_errors_display(self, obj):
        """Show validation errors if any."""
        import json
        if not obj.validation_errors:
            return '-'
        return format_html(
            '<pre style="max-height: 200px; overflow: auto; color: red;">{}</pre>',
            json.dumps(obj.validation_errors, indent=2)
        )
    validation_errors_display.short_description = 'Validation Errors'

    def auto_corrected_fields_display(self, obj):
        """Show list of auto-corrected fields."""
        if not obj.auto_corrected_fields:
            return '-'
        return ', '.join(obj.auto_corrected_fields)
    auto_corrected_fields_display.short_description = 'Auto-Corrected Fields'

    def has_add_permission(self, request):
        """Disable adding instances through admin - use wizard instead."""
        return False

    def has_change_permission(self, request, obj=None):
        """Allow viewing but instances should be edited through wizard."""
        return True

    def has_delete_permission(self, request, obj=None):
        """Allow deletion through admin."""
        return True
