"""
Django settings for sdc4 project.

Generated by SDCStudio AppGen (Enterprise Stack).
"""
from pathlib import Path
from decouple import config, Csv
import dj_database_url
BASE_DIR = Path(__file__).resolve().parent.parent
SECRET_KEY = config('SECRET_KEY', default='django-insecure-sdc4-key')
DEBUG = config('DEBUG', default=True, cast=bool)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())
INSTALLED_APPS = ['test_data3', 'django.contrib.admin', 'django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.sessions', 'django.contrib.messages', 'django.contrib.staticfiles', 'django.contrib.sites', 'crispy_forms', 'crispy_bootstrap5', 'rest_framework', 'django_htmx', 'widget_tweaks', 'allauth', 'allauth.account', 'allauth.socialaccount', 'allauth.socialaccount.providers.openid_connect', 'core', 'statepopulation']
MIDDLEWARE = ['django.middleware.security.SecurityMiddleware', 'whitenoise.middleware.WhiteNoiseMiddleware', 'django.contrib.sessions.middleware.SessionMiddleware', 'django.middleware.common.CommonMiddleware', 'django.middleware.csrf.CsrfViewMiddleware', 'django.contrib.auth.middleware.AuthenticationMiddleware', 'django.contrib.messages.middleware.MessageMiddleware', 'django.middleware.clickjacking.XFrameOptionsMiddleware', 'django_htmx.middleware.HtmxMiddleware', 'allauth.account.middleware.AccountMiddleware']
ROOT_URLCONF = 'sdc4.urls'
TEMPLATES = [{'BACKEND': 'django.template.backends.django.DjangoTemplates', 'DIRS': [BASE_DIR / 'templates'], 'APP_DIRS': True, 'OPTIONS': {'context_processors': ['django.template.context_processors.debug', 'django.template.context_processors.request', 'django.contrib.auth.context_processors.auth', 'django.contrib.messages.context_processors.messages']}}]
WSGI_APPLICATION = 'sdc4.wsgi.application'
DATABASES = {'default': dj_database_url.config(default=config('DATABASE_URL', default='sqlite:///db.sqlite3'), conn_max_age=600)}
AUTH_PASSWORD_VALIDATORS = [{'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'}, {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'}, {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'}, {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'}]
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'mediafiles'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap5'
CRISPY_TEMPLATE_PACK = 'bootstrap5'
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60
GRAPHDB_URL = config('GRAPHDB_URL', default='http://localhost:7200')
GRAPHDB_REPOSITORY = config('GRAPHDB_REPOSITORY', default='sdc4_rdf')
GRAPHDB_USER = config('GRAPHDB_USER', default='admin')
GRAPHDB_PASSWORD = config('GRAPHDB_PASSWORD', default='admin123')
SIRIX_URL = config('SIRIX_URL', default='https://localhost:9443')
SIRIX_USER = config('SIRIX_USER', default='admin')
SIRIX_PASSWORD = config('SIRIX_PASSWORD', default='admin123')
SIRIX_DATABASE = config('SIRIX_DATABASE', default='sdc4_temporal')
SIRIX_VERIFY_SSL = config('SIRIX_VERIFY_SSL', default=False, cast=bool)
KEYCLOAK_URL = config('KEYCLOAK_URL', default='http://localhost:8080')
KEYCLOAK_REALM = config('KEYCLOAK_REALM', default='sdc4')
KEYCLOAK_CLIENT_ID = config('KEYCLOAK_CLIENT_ID', default='sdc4-web')
KEYCLOAK_CLIENT_SECRET = config('KEYCLOAK_CLIENT_SECRET', default='changeme')
SITE_ID = 1
AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.ModelBackend', 'allauth.account.auth_backends.AuthenticationBackend']
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_EMAIL_REQUIRED = True
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
SOCIALACCOUNT_PROVIDERS = {'openid_connect': {'APPS': [{'provider_id': 'keycloak', 'name': 'Keycloak', 'client_id': KEYCLOAK_CLIENT_ID, 'secret': KEYCLOAK_CLIENT_SECRET, 'settings': {'server_url': f'{KEYCLOAK_URL}/realms/{KEYCLOAK_REALM}/.well-known/openid-configuration'}}]}}
SDC4_STACK = config('SDC4_STACK', default='enterprise')