# Generated by Django for SDC4 Generic Storage

from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models
import django.contrib.postgres.fields
import django.contrib.postgres.indexes


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenericInstance',
            fields=[
                ('instance_id', models.CharField(help_text='Instance ID - Format: i-{cuid} or i-ev-{cuid}', max_length=50, primary_key=True, serialize=False)),
                ('dm_ct_id', models.CharField(db_index=True, help_text='Data Model CT_ID this instance belongs to', max_length=50)),
                ('dm_label', models.CharField(help_text='Human-readable data model name', max_length=200)),
                ('xml_content', models.TextField(help_text='Complete validated XML content (authoritative source)')),
                ('json_instance', models.JSONField(blank=True, help_text='JSON representation for JSONB queries', null=True)),
                ('search_text', models.TextField(blank=True, help_text='Concatenated searchable text from all fields')),
                ('rdf_content', models.TextField(blank=True, help_text='RDF/Turtle representation of the instance')),
                ('validation_status', models.CharField(choices=[('valid', 'Valid'), ('valid_with_ev', 'Valid with Exceptional Values')], default='valid', help_text='Validation status', max_length=20)),
                ('validation_errors', models.JSONField(blank=True, help_text='Validation errors (if any)', null=True)),
                ('auto_corrected_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='List of field labels that were auto-corrected with EVs', size=None)),
                ('rdf_sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed'), ('disabled', 'Disabled')], default='pending', help_text='RDF triplestore synchronization status', max_length=20)),
                ('graphdb_graph_uri', models.CharField(blank=True, help_text='Named graph URI in GraphDB', max_length=255)),
                ('rdf_uploaded_at', models.DateTimeField(blank=True, help_text='Timestamp of last successful RDF upload', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Generic Instance',
                'verbose_name_plural': 'Generic Instances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='genericinstance',
            index=models.Index(fields=['dm_ct_id', '-created_at'], name='generic_sto_dm_ct_i_8a3b9e_idx'),
        ),
        migrations.AddIndex(
            model_name='genericinstance',
            index=models.Index(fields=['validation_status'], name='generic_sto_validat_2e8f5c_idx'),
        ),
        migrations.AddIndex(
            model_name='genericinstance',
            index=models.Index(fields=['rdf_sync_status'], name='generic_sto_rdf_syn_6c7d4a_idx'),
        ),
        migrations.AddIndex(
            model_name='genericinstance',
            index=django.contrib.postgres.indexes.GinIndex(fields=['json_instance'], name='generic_sto_json_in_9f8e7b_gin'),
        ),
    ]
